### ISSUE TITLE
UPM support?

### ISSUE THREAD

**Issue by STARasGAMES** [AlexeyPerov/Unity-Dependencies-Hunter#2]
Hi
Didn't test this script yet.

But it would be awesome to have UPM support!

Here is how I accomplish this:
https://github.com/STARasGAMES/Unity-package-repo-setup-template

Cheers!

UPD
I tested it and it does what I expected. Good stuff

**Comment by STARasGAMES** [comment]
Ok, I could make this, but this will completely change your current project structure. Example of structure I sent before. 
Are you ok with this @AlexeyPerov ?

**Comment by AlexeyPerov** [comment]
Yes, absolutely! @STARasGAMES
