### ISSUE TITLE
Unity.VisualScripting is required in the newest version.

### ISSUE THREAD

**Issue by adamgryu** [AlexeyPerov/Unity-Dependencies-Hunter#24]
I noticed the "using Unity.VisualScripting;" was added in the latest version. I think this was a mistake. It requires the project to add the Visual Scripting package to work now.
https://github.com/AlexeyPerov/Unity-Dependencies-Hunter/pull/21/commits/20cf332bfcc50b19e8b62ec0354bdc88ebdc455d

**Comment by Zammy** [comment]
+1 Same problem. I am going to use a version from previous commit.

**Comment by AlexeyPerov** [comment]
removed in this PR https://github.com/AlexeyPerov/Unity-Dependencies-Hunter/pull/25 by @fwild

**Comment by AlexeyPerov** [comment]
issue fixed https://github.com/AlexeyPerov/Unity-Dependencies-Hunter/pull/25
