### ISSUE TITLE
rename "Assets/Find References In Project" because of new unity issue

### ISSUE THREAD

**Issue by YKucheriavchenko** [AlexeyPerov/Unity-Dependencies-Hunter#27]
New unity already have the menu item with the same name

**Comment by ekrem-qb** [comment]
You can use this fork: [NordlightPer/Unity-Dependencies-Hunter](https://github.com/NordlightPer/Unity-Dependencies-Hunter/tree/upm) until @AlexeyPerov merges it

**Comment by AlexeyPerov** [comment]
fixed by https://github.com/AlexeyPerov/Unity-Dependencies-Hunter/pull/28
