### ISSUE TITLE
To much logs in the console?

### ISSUE THREAD

**Issue by STARasGAMES** [AlexeyPerov/Unity-Dependencies-Hunter#4]
Runnin analysis on empty project produces 240 log messages:
![image](https://user-images.githubusercontent.com/23558898/125818919-d90e1a0e-f32f-4d94-9b0b-dff2cc939f63.png)

Maybe it would be better to log one big message instead

**Comment by STARasGAMES** [comment]
Btw right now I'm working on making project UPM compatible, so please, don't rush fixing this issue if you decide to :)

**Comment by AlexeyPerov** [comment]
Fixed (now it is outputting in a single call)
